### ISSUE TITLE
Enums are not supported in LogEvent.AppendGeneric

### ISSUE THREAD

**Issue by y-skindersky** [Abc-Arbitrage/ZeroLog#19]
Do you have any plans regarding enumerations support? Any static cache or anything else?

**Comment by ltrzesniewski** [comment]
Yes, that's a feature which should definitely be added, but we don't have any precise plans at the moment.

This requires some design work beforehand, as enum types would need to be registered in advance in order to avoid allocations. We'll also need a way to *efficiently* transmit a type handle in the buffer. which is not as straightforward as it sounds. I can think of a few different approaches that would need to be benchmarked.

Finally, we'll probably have to add an `AppendEnum<T>` method for performance reasons, and `AppendGeneric<T>` would call it as a last case resort before failing.

**Comment by ltrzesniewski** [comment]
I'll likely bump the target platform to net452 after implementing this, as I'd like to use [this](https://github.com/Fody/ExtraConstraints) thing, which doesn't support net45 anymore.

BTW I did the benchmarks part. We now have a way to serialize a type handle.

**Comment by ltrzesniewski** [comment]
This is now deployed in v1.1.0.
