### ISSUE TITLE
Comparison with other projects based on source generators

### ISSUE THREAD

**Issue by kolpav** [Abc-Arbitrage/ZeroLog#56]
Hello, at one point I would like to replace logging library I currently use with something simpler so I have been looking around and there are few promising projects implementing logging using generated code at build time  my quick impression was that it is **the** solution, having access to all advanced functionality while not paying any cost at run time.
So I thought that new projects aiming at performance would be all source generated as its technology enabling things which were not possible before.
Were you considering going that way when you were building this project?
Don't take this as critique the project looks really high quality and having more than one or two options is always better. Actually you might be as fast due to asynchronous architecture you use. Also I haven't had time to actually try source generators so all I know is from skimming few articles about it.

**Comment by ocoanet** [comment]
Hello.

I suppose you have in mind the [strongly-typed log methods generation](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator).

Yes, we considered supporting this pattern, but:
- This pattern is quite cumbersome to apply: you need to define a dedicated method for every log line. We would probably not use it in our own codebase.
- ZeroLog would not benefit much from this pattern because log message formatting is run in the dedicated log processor thread, not in the thread that creates the log event. Yet, it could still very slightly improve the logging performance by allowing a few compile time tweaks.
- Also, the interpolated string handlers are quite useful to avoid invoking methods when the expected log level is not reached, because they generated a top level `if` statement. In this regard, interpolated string handlers already perform very simple compile time adjustments.

We still might decide to support this pattern in the future if we need to use it in our codebase, or if we feel that this feature is really expected by the .NET community.

**Comment by kolpav** [comment]
Not exactly at the time of writing I couldn't find the project I had in mind but I probably meant this https://www.postsharp.net/metalama/features#transforming-code and kind of mixed few projects I have seen together in my head.

There are source based DI and mapping projects which I have tried and they work nicely and I wrongly assumed there is also one for logging so now I am just throwing few ideas:

- it seems like some of the work could be done at compile time turning plain string interpolation into structured log
- generating `ToString` overloads instead of doing json serialization at runtime which I assume must use reflection somewhere while providing very little type information to compiler
- Not having to type same logging logic multiple times like putting  `[LogTimeExecution]` on methods which you might delete after you are done
- Be able to specify log targets via attribute not having to fiddle with nlog xmls or jsons like `[LogToEmail]` for high severity errors
- Detailed stack trace of just your own code without noise, you could use colors per project, indentations and probably much more

When I have more time I would like to measure how much of a difference having code hotpaths like mapping, DI and logging replaced with their generated alternatives improves performance.
Anyway there is nothing actionable on this issue so feel free to close:)

**Comment by kolpav** [comment]
The structured logging pattern looks exactly like something nobody would like to type.

**Comment by ocoanet** [comment]
So you are interested in AOP-style, compile-time generated logging?

In my view this kind of feature is outside the scope of ZeroLog. You can already use existing tools like PostSharp to create your own aspects / attributes that generate logs using the logging library of your choice.

**Comment by kolpav** [comment]
Sure, I was not suggesting for you to change anything I skimmed through the code and it seamed really neat while taking advantage of new c# features so I wanted to know your opinion on [source code generators ](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) and its application in logging.
I have read the code again and think I have general idea how it works which is not something I can say I was able to do on second read of other logging libraries code.
I think it will be my library of choice as extending your code with my project specific features seems much more appealing than fiddling with xamls, yamls or jsons.

Thank you for taking time to answer my questions.
